name: moa_jittor
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - libstdcxx-ng=12.2.0
  - libgcc-ng
  - numpy
  - cmake
  - pip

  - pytorch-cpu
  - cpuonly     

  - matplotlib
  - seaborn
  - scipy

  - tqdm

  - pip:
      - jittor
      
      - tensorboardX
      - tensorboard
      
      - modelscope
      - tiktoken
      - blobfile
      
      - fire
      
      - pynvml
