name: moa_jittor
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - libstdcxx-ng=12.2.0
  - libgcc-ng
  - numpy
  - cmake
  - pip:
      - jittor
      - torch==2.0.1
      - tensorboardX
      - modelscope
      - tiktoken
      - blobfile 